main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

penggalangan_dana/urls.py
from django.urls import path
from .views import form_pd_rumahibadah, index, add_pd, form_kesehatan, form_rumah_ibadah, form_pd, baru_kesehatan, tidak_baru_kesehatan, baru_rumah_ibadah, tidak_baru_rumah_ibadah, daftar_pd_pribadi, detail_pd, form_pd_kes, form_pd_rumahibadah

app_name = "penggalangan_dana"

urlpatterns = [
    path('',index, name='index'),
    path('add-pd/', add_pd, name='add_pd'),
    path('form-kesehatan/', form_kesehatan, name='form_kesehatan'),
    path('form-rumah_ibadah/', form_rumah_ibadah, name='form_rumah_ibadah'),
    path('form-pd/', form_pd, name='form_pd'),
    path('form-pd-kes/', form_pd_kes, name='form_pd_kes'),
    path('form-pd-rumahibadah/', form_pd_rumahibadah, name='form_pd_rumahibadah'),
    path('form-kesehatan/baru/', baru_kesehatan, name='baru_kesehatan'),
    path('form-kesehatan/tidak-baru/', tidak_baru_kesehatan, name='tidak_baru_kesehatan'),
    path('form-rumah_ibadah/baru/', baru_rumah_ibadah, name='baru_rumah_ibadah'),
    path('form-rumah_ibadah/tidak-baru/', tidak_baru_rumah_ibadah, name='tidak_baru_rumah_ibadah'),
    path('form-pd/daftar-pd-pribadi/', daftar_pd_pribadi, name='daftar_pd_pribadi'),
    path('detail-pd', detail_pd, name='detail_pd'),
]

sidona19/urls.py
from django.contrib import admin
from django.urls import include, path
import trigger3.urls as trigger3

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger3/', include(trigger3)),
    path('', include('login.urls')),
     path('trigger5/', include('trigger5.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('donasi/', include('donasi.urls')),
    path('penggalangan_dana/', include('penggalangan_dana.urls')),
    path('penyakit_komorbid/',include('penyakit_komorbid.urls')),
]

penggalangan_dana/models.py
from django.db import models

# Create your models here.

penggalangan_dana/views.py
from django.http import response
from django.shortcuts import render
from django.db import connection
from collections import namedtuple

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def index(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to sidona")
    return render(request,'index.html')

def add_pd(request):

    response = {}
    cursor = connection.cursor()
    cursor.execute("set search_path to sidona")
    cursor.execute("select nama_kategori from kategori_pd")
    list_kategori = namedtuplefetchall(cursor)
    response['categories'] = list_kategori

    return render(request,'form_addpd.html',response)

def form_kesehatan(request):
    return render(request,'form_kesehatan.html')

def form_rumah_ibadah(request):
    return render(request,'form_rumah_ibadah.html')

def get_input_pd(request):
    input = request.POST


def form_pd(request):

    return render(request,'form_pd.html')

def form_pd_kes(request):
    

    if request.method == 'POST':

        response = {}
        nik = request.POST['nik']
        response['nik'] = nik
        nama = request.POST['nama']
        response['nama'] = nama
        tanggallahir = request.POST['tanggal_lahir']
        response['tanggal_lahir'] = tanggallahir
        alamat = request.POST['alamat']
        response['alamat'] = alamat
        pekerjaan = request.POST['pekerjaan']
        response['pekerjaan'] = pekerjaan

        cursor = connection.cursor()
        cursor.execute("set search_path to sidona")
        cursor.execute("INSERT INTO PASIEN VALUES(%s, %s, %s, %s, %s)", [nik, nama, tanggallahir, alamat, pekerjaan])

        cursor.execute("select * from pasien where nik = %s", [nik])
        # pasien = cursor.fetchone()[0]
        pasien = namedtuplefetchall(cursor)
        response['kesehatan'] = pasien

        # cursor2 = connection.cursor()
        # cursor2.execute("set search_path to sidona")
        # cursor2.execute("")

        # cursor.execute("select id from penggalangan_dana_pd order by id asc")
        # id_pd_view = namedtuplefetchall(cursor)

    return render(request,'form_pd_kesehatan.html', response)

def form_pd_rumahibadah(request):
    

    if request.method == 'POST':

        response = {}
        no_serti = request.POST['no_serti']
        response['no_serti'] = no_serti
        nama_ri = request.POST['nama-ri']
        # response['nama-ri'] = nama_ri
        alamat = request.POST['alamat']
        # response['alamat'] = alamat
        jenis = request.POST['jenis']
        # response['jenis'] = jenis

        cursor = connection.cursor()
        cursor.execute("set search_path to sidona")
        cursor.execute("INSERT INTO rumah_ibadah VALUES(%s, %s, %s, %s)", [no_serti, nama_ri, alamat, jenis])

        cursor.execute("select * from rumah_ibadah where nosertifikat = %s", [no_serti])
        rumah_ibadah = namedtuplefetchall(cursor)
        response['rumah_ibadah'] = rumah_ibadah

        cursor2 = connection.cursor()
        cursor2.execute("set search_path to sidona")
        cursor2.execute("select * from kategori_aktivitas_pd_rumah_ibadah")
        list_kategori_ri = namedtuplefetchall(cursor2)
        response['kategori_ri'] = list_kategori_ri

    return render(request,'form_pd_rumahibadah.html', response)

def validateNIK(nik):
    cursor = connection.cursor()
    cursor.execute("set search_path to sidona")
    cursor.execute("select * from pasien")
    list_nik = namedtuplefetchall(cursor)


def baru_kesehatan(request):
    return render(request,'baru_kesehatan.html')

def tidak_baru_kesehatan(request):
    return render(request,'tidak_baru_kesehatan.html')

def baru_rumah_ibadah(request):
    return render(request,'baru_rumah_ibadah.html')

def tidak_baru_rumah_ibadah(request):
    return render(request,'tidak_baru_rumah_ibadah.html')

def daftar_pd_pribadi(request):
    return render(request,'daftar_pd_pribadi.html')

def detail_pd(request):
    return render(request,'detail_pd.html')

penggalangan_dana/templates/baru_kesehatan.html
{% extends 'base_pd.html' %}    

{% block content %}

<div class="container">
    <h2 class="text-center" style="padding: 40px;"><b>Form Pasien</b></h2>
    <form action="{% url 'penggalangan_dana:form_pd_kes' %}" method="POST">
        {% csrf_token %}
        <h5 style="margin-bottom: 20px;">Identitas Pasien</h5>
        <div class="form-group">
            <label for="nik">NIK</label>
            <input type="text" name="nik" class="form-control" placeholder="Masukkan NIK Pasien" required>
        </div>
        <div class="form-group">
            <label for="nama">Nama</label>
            <input type="text" name="nama" class="form-control" placeholder="Masukkan Nama Pasien" required>
        </div>
        <div class="form-group">
            <label for="tanggal_lahir">Tanggal Lahir</label>
            <input type="date" name="tanggal_lahir" class="form-control" placeholder="Masukkan Tanggal Lahir Pasien" required>
        </div>
        <div class="form-group">
            <label for="alamat">Alamat</label>
            <input type="text" name="alamat" class="form-control" placeholder="Masukkan Alamat Pasien" required>
        </div>
        <div class="form-group">
            <label for="pekerjaan">Pekerjaan</label>
            <input type="text" name="pekerjaan" class="form-control" placeholder="Masukkan Pekerjaan Pasien" required>
        </div>
        <div class="col text-center" style="margin-top:50px; margin-bottom: 100px;">
            <button id="buttonId" class="btn btn-primary" type="submit">Next</button>
            <!-- <a type="button" class="btn btn-primary justify-content-center" href="{% url 'penggalangan_dana:form_pd' %}">Next</a> -->
        </div>
    
    </form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>


<!-- <script type = "text/javascript" language = "javascript">
 jQuery(document).ready(function() {
    jQuery("#buttonId").click(function() {
        if ($("#form-id").valid()){
            console.log("valid")
            window.location = window.location = "/penggalangan_dana/form-pd/";
        }
        
    });
 });
</script> -->

{% endblock content %}

penggalangan_dana/templates/baru_rumah_ibadah.html
{% extends 'base_pd.html' %}    

{% block content %}

<div class="container">
    <h2 class="text-center" style="padding: 40px;"><b>Form Rumah Ibadah</b></h2>
    <form action="{% url 'penggalangan_dana:form_pd_rumahibadah' %}" method="POST">
        {% csrf_token %}
        <h5 style="margin-bottom: 20px;">Informasi Rumah Ibadah</h5>
        <div class="form-group">
            <label for="">Nomor Sertifikat</label>
            <input type="text" name="no_serti" class="form-control" placeholder="Masukkan Nomor Sertifikat Rumah Ibadah" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Nama</label>
            <input type="text" name="nama-ri" class="form-control"placeholder="Masukkan Nama Rumah Ibadah" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Alamat</label>
            <input type="text" name="alamat" class="form-control"placeholder="Masukkan Alamat Rumah Ibadah" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Jenis</label>
            <input type="text" name="jenis" class="form-control"placeholder="Masukkan Jenis Rumah Ibadah" required>
        </div>
        <div class="col text-center" style="margin-top:50px; margin-bottom: 100px;">
            <button id="buttonId" class="btn btn-primary" type="submit" href="{% url 'penggalangan_dana:form_pd' %}">Next</button>
            <!-- <a type="button" class="btn btn-primary justify-content-center" href="{% url 'penggalangan_dana:form_pd' %}">Next</a> -->
        </div>
        <!-- <input type="submit" class="btn btn-primary justify-content-center" href="{% url 'penggalangan_dana:form_pd' %}"> -->
    </form>
</div>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

<script type = "text/javascript" language = "javascript">
 jQuery(document).ready(function() {
    jQuery("#buttonId").click(function() {
        window.location = window.location = "/penggalangan_dana/form-pd/";;
    
    });
 });
</script> -->

{% endblock content %}

penggalangan_dana/templates/daftar_pd_pribadi.html
{% extends 'base_pd.html' %}    

{% block content %}

<div class="container">
    <h2 class="text-center" style="padding: 40px;"><b>Halaman Daftar Penggalangan Dana Pribadi (POV Penggalang Dana)</b></h2>
    <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Judul</th>
            <th scope="col">Kota</th>
            <th scope="col">Prov</th>
            <th scope="col">Tanggal Aktif Awal</th>
            <th scope="col">Deadline</th>
            <th scope="col">Sisa Hari</th>
            <th scope="col">Target Dana</th>
            <th scope="col">Kategori</th>
            <th scope="col">Status Verifikasi</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">K-001</th>
            <td>Ayo bantu Zulfahri menghadapi penyakit Demam Berdarahnya!</td>
            <td>Bandung</td>
            <td>Jawa Barat</td>
            <td>15 November 2021</td>
            <td>7 Desember 2021</td>
            <td>20 hari</td>
            <td>Rp 1.000.000,-</td>
            <td>Kesehatan</td>
            <td>Sudah Terverifikasi</td>
            <td>
                <!-- <button id="detail-btn" type="button" class="" style="margin-bottom: 20px;">Detail</button> -->
                <a type="button" class="btn btn-primary" style="margin-bottom: 20px;" href="{% url 'penggalangan_dana:detail_pd' %}">Detail</a>
                <!-- <button type="button" class="btn btn-success" style="margin-bottom: 20px;">Cairkan</button> -->
                <a type="button" class="btn btn-success" style="margin-bottom: 20px;" href="/trigger5/pencairan">Cairkan</a>
            </td>
          </tr>
          <tr>
            <th scope="row">R-001</th>
            <td>Bangun masjid untuk Desa Maju</td>
            <td>Jakarta</td>
            <td>DKI Jakarta</td>
            <td></td>
            <td>10 Desember 2021</td>
            <td></td>
            <td>Rp 10.000.000,-</td>
            <td>Rumah Ibadah</td>
            <td>Belum Terverifikasi</td>
            <td>
                <!-- <button id="detail-btn" type="button" class="btn btn-primary" style="margin-bottom: 20px;">Detail</button> -->
                <a type="button" class="btn btn-primary" style="margin-bottom: 20px;" href="{% url 'penggalangan_dana:detail_pd' %}">Detail</a>
                <button type="button" class="btn btn-danger" style="margin-bottom: 20px;">Delete</button>
            </td>
          </tr>
        </tbody>
        </table>
        <p style="font-weight: bold;">Jumlah Penggalangan Dana: 2</p>
        <p style="font-weight: bold;">Jumlah Penggalangan Dana Aktif: 1</p>
</div>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

<script type = "text/javascript" language = "javascript">
 jQuery(document).ready(function() {
    jQuery("#detail-btn").click(function() {
        window.location = window.location = "/penggalangan_dana/detail-pd";;
    
    });
 });
</script> -->

{% endblock content %}

penggalangan_dana/templates/form_pd.html
{% extends 'base_pd.html' %}    

{% block content %}

<div class="container">
    <h2 class="text-center" style="padding: 40px;"><b>Form Penggalangan Dana</b></h2>
    <form action="{% url 'penggalangan_dana:daftar_pd_pribadi' %}" method="POST">
        {% csrf_token %}
        <h5 style="margin-bottom: 20px;">Informasi Umum Penggalangan Dana</h5>
        <div class="form-group">
            <label for="">ID Penggalangan Dana</label>
            <input type="text" class="form-control" placeholder="K-001" disabled>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email Penggalangan Dana</label>
            <input type="text" class="form-control"placeholder="hskey5@newsvine.com" disabled>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Judul</label>
            <input type="text" class="form-control"placeholder="Masukkan Judul Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Deskripsi</label>
            <input type="text" class="form-control"placeholder="Masukkan Deskripsi Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Kota</label>
            <input type="text" class="form-control"placeholder="Masukkan Kota Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Provinsi</label>
            <input type="text" class="form-control"placeholder="Masukkan Provinsi Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Deadline Penggalangan Dana</label>
            <input type="date" class="form-control"placeholder="Masukkan Deadline Penggalangan Dana" required>
        </div>
        <div class="form-group" style="margin-bottom: 50px;">
            <label for="exampleInputEmail1">Jumlah Target Dana (Rupiah)</label>
            <input type="text" class="form-control"placeholder="Masukkan Jumlah Target Dana Penggalangan Dana" required>
        </div>
        
        <h5 style="margin-bottom: 20px;">Informasi Tambahan Penggalangan Dana</h5>
        <div class="form-group">
            <label for="">Kategori</label>
            <input type="text" class="form-control" placeholder="Kesehatan" disabled>
        </div>
        <div class="form-group">
            <label for="">NIK Pasien</label>
            <input type="text" class="form-control" placeholder="320107474" disabled>
        </div>
        <div class="form-group">
            <label for="">Nama Pasien</label>
            <input type="text" class="form-control" placeholder="Dian" disabled>
        </div>
        <div class="form-group">
            <label for="">Nomor Sertifikat Rumah Ibadah</label>
            <input type="text" class="form-control" placeholder="RI-06" disabled>
        </div>
        <div class="form-group">
            <label for="e">Kategori Aktivitas</label>
            <select id = "kategori" class="custom-select" required>
                <option value="">Pilih Kategori</option>
                <option value="1">Belajar</option>
                <option value="2">Menyapu</option>
                <option value="3">Mengepel</option>
                <option value="4">Berdoa</option>
                <option value="5">Bersih-bersih</option>
              </select>
            <!-- <a id="buttonId" class="btn btn-primary btn-lg active d-flex justify-content-center" role="button" aria-pressed="true">Next</a> -->
        </div>
        <div class="form-group">
            <label for="">Berkas Penggalangan Dana</label>
            <input type="text" class="form-control" placeholder="Masukkan Link Berkas Penggalangan Dana" required>
        </div>
        <div class="col text-center" style="margin-top: 50px; margin-bottom: 100px;">
            <button id="buttonId" class="btn btn-primary" type="submit">CREATE</button>
            <!-- <a type="button" class="btn btn-primary justify-content-center" href="{% url 'penggalangan_dana:daftar_pd_pribadi' %}">CREATE</a> -->
        </div>
    </form>
</div>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

<script type = "text/javascript" language = "javascript">
 jQuery(document).ready(function() {
    jQuery("#buttonId").click(function() {
        window.location = window.location = "/penggalangan_dana/form-pd/daftar-pd-pribadi/";
    });
 });
</script> -->

{% endblock content %}

penggalangan_dana/templates/form_pd_kesehatan.html
{% extends 'base_pd.html' %}    

{% block content %}

<div class="container">
    <h2 class="text-center" style="padding: 40px;"><b>Form Penggalangan Dana</b></h2>
    <form action="{% url 'penggalangan_dana:daftar_pd_pribadi' %}" method="POST">
        {% csrf_token %}
        <h5 style="margin-bottom: 20px;">Informasi Umum Penggalangan Dana</h5>
        <div class="form-group">
            <label for="">ID Penggalangan Dana</label>
            <input type="text" class="form-control" placeholder="K-001" disabled>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email Penggalangan Dana</label>
            <input type="text" class="form-control"placeholder="hskey5@newsvine.com" disabled>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Judul</label>
            <input type="text" class="form-control"placeholder="Masukkan Judul Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Deskripsi</label>
            <input type="text" class="form-control"placeholder="Masukkan Deskripsi Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Kota</label>
            <input type="text" class="form-control"placeholder="Masukkan Kota Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Provinsi</label>
            <input type="text" class="form-control"placeholder="Masukkan Provinsi Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Deadline Penggalangan Dana</label>
            <input type="date" class="form-control"placeholder="Masukkan Deadline Penggalangan Dana" required>
        </div>
        <div class="form-group" style="margin-bottom: 50px;">
            <label for="exampleInputEmail1">Jumlah Target Dana (Rupiah)</label>
            <input type="text" class="form-control"placeholder="Masukkan Jumlah Target Dana Penggalangan Dana" required>
        </div>
        
        <h5 style="margin-bottom: 20px;">Informasi Tambahan Penggalangan Dana</h5>
        <div class="form-group">
            <label for="">Kategori</label>
            <input type="text" class="form-control" placeholder="Kesehatan" disabled>
        </div>
        <div class="form-group">
            <label for="">NIK Pasien</label>
            <input type="text" class="form-control" placeholder={{nik}} disabled>
        </div>
        <div class="form-group">
            <label for="">Nama Pasien</label>
            <input type="text" class="form-control" placeholder={{nama}} disabled>
        </div>
        <div class="form-group">
            <label for="">Berkas Penggalangan Dana</label>
            <input type="text" class="form-control" placeholder="Masukkan Link Berkas Penggalangan Dana" required>
        </div>
        <div class="col text-center" style="margin-top: 50px; margin-bottom: 100px;">
            <button id="buttonId" class="btn btn-primary" type="submit">CREATE</button>
            <!-- <a type="button" class="btn btn-primary justify-content-center" href="{% url 'penggalangan_dana:daftar_pd_pribadi' %}">CREATE</a> -->
        </div>
    </form>
</div>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

<script type = "text/javascript" language = "javascript">
 jQuery(document).ready(function() {
    jQuery("#buttonId").click(function() {
        window.location = window.location = "/penggalangan_dana/form-pd/daftar-pd-pribadi/";
    });
 });
</script> -->

{% endblock content %}

penggalangan_dana/templates/form_pd_rumahibadah.html
{% extends 'base_pd.html' %}    

{% block content %}

<div class="container">
    <h2 class="text-center" style="padding: 40px;"><b>Form Penggalangan Dana</b></h2>
    <form action="{% url 'penggalangan_dana:daftar_pd_pribadi' %}" method="POST">
        {% csrf_token %}
        <h5 style="margin-bottom: 20px;">Informasi Umum Penggalangan Dana</h5>
        <div class="form-group">
            <label for="">ID Penggalangan Dana</label>
            <input type="text" class="form-control" placeholder="RI-001" disabled>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email Penggalangan Dana</label>
            <input type="text" class="form-control"placeholder="hskey5@newsvine.com" disabled>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Judul</label>
            <input type="text" class="form-control"placeholder="Masukkan Judul Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Deskripsi</label>
            <input type="text" class="form-control"placeholder="Masukkan Deskripsi Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Kota</label>
            <input type="text" class="form-control"placeholder="Masukkan Kota Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Provinsi</label>
            <input type="text" class="form-control"placeholder="Masukkan Provinsi Penggalangan Dana" required>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Deadline Penggalangan Dana</label>
            <input type="date" class="form-control"placeholder="Masukkan Deadline Penggalangan Dana" required>
        </div>
        <div class="form-group" style="margin-bottom: 50px;">
            <label for="exampleInputEmail1">Jumlah Target Dana (Rupiah)</label>
            <input type="text" class="form-control"placeholder="Masukkan Jumlah Target Dana Penggalangan Dana" required>
        </div>
        
        <h5 style="margin-bottom: 20px;">Informasi Tambahan Penggalangan Dana</h5>
        <div class="form-group">
            <label for="">Kategori</label>
            <input type="text" class="form-control" placeholder="Rumah Ibadah" disabled>
        </div>
        <div class="form-group">
            <label for="">Nomor Sertifikat Rumah Ibadah</label>
            <input type="text" class="form-control" placeholder={{no_serti}} disabled>
        </div>
        <div class="form-group">
            <label for="e">Kategori Aktivitas</label>
            <select id = "kategori" class="custom-select" required>
                <option value="">Pilih Kategori</option>
                {% for kategori in kategori_ri %}
                    <option value={{kategori.nama}}>{{kategori.nama}}</option>

                {% endfor %}
                <!-- <option value="1">Belajar</option>
                <option value="2">Menyapu</option>
                <option value="3">Mengepel</option>
                <option value="4">Berdoa</option>
                <option value="5">Bersih-bersih</option> -->
              </select>
            <!-- <a id="buttonId" class="btn btn-primary btn-lg active d-flex justify-content-center" role="button" aria-pressed="true">Next</a> -->
        </div>
        <div class="form-group">
            <label for="">Berkas Penggalangan Dana</label>
            <input type="text" class="form-control" placeholder="Masukkan Link Berkas Penggalangan Dana" required>
        </div>
        <div class="col text-center" style="margin-top: 50px; margin-bottom: 100px;">
            <button id="buttonId" class="btn btn-primary" type="submit">CREATE</button>
            <!-- <a type="button" class="btn btn-primary justify-content-center" href="{% url 'penggalangan_dana:daftar_pd_pribadi' %}">CREATE</a> -->
        </div>
    </form>
</div>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

<script type = "text/javascript" language = "javascript">
 jQuery(document).ready(function() {
    jQuery("#buttonId").click(function() {
        window.location = window.location = "/penggalangan_dana/form-pd/daftar-pd-pribadi/";
    });
 });
</script> -->

{% endblock content %}

penggalangan_dana/templates/tidak_baru_kesehatan.html
{% extends 'base_pd.html' %}    

{% block content %}

<div class="container">
    <h2 class="text-center" style="padding: 40px;"><b>Cek Pasien yang Terdaftar</b></h2>
    <form action="{% url 'penggalangan_dana:form_pd_kes' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="">NIK Pasien</label>
            <input type="text" name="nik" class="form-control" placeholder="Masukkan NIK Pasien" required>
        </div>
        <div class="col text-center">
            <button id="buttonId" class="btn btn-primary" type="submit">Check</button>
        </div>

    </form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

<!-- <script type = "text/javascript" language = "javascript">
 jQuery(document).ready(function() {
    jQuery("#buttonId").click(function() {
        window.location = window.location = "/penggalangan_dana/form-pd/";;
    
    });
 });
</script> -->

{% endblock content %}

penggalangan_dana/templates/tidak_baru_rumah_ibadah.html
{% extends 'base_pd.html' %}    

{% block content %}

<div class="container">
    <h2 class="text-center" style="padding: 40px;"><b>Cek Rumah Ibadah yang Terdaftar</b></h2>
    <form action="{% url 'penggalangan_dana:form_pd' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="">Nomor Sertifikat Rumah Ibadah</label>
            <input type="text" class="form-control" placeholder="Masukkan Nomor Sertifikat Rumah Ibadah" required>
        </div>
        <div class="col text-center">
            <button id="buttonId" class="btn btn-primary" type="submit">Check</button>
        </div>
    
    </form>
</div>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

<script type = "text/javascript" language = "javascript">
 jQuery(document).ready(function() {
    jQuery("#buttonId").click(function() {
        window.location = window.location = "/penggalangan_dana/form-pd/";;
    
    });
 });
</script> -->

{% endblock content %}