donasi/urls.py
from django.urls import path
from .views import donasi_index, donasi_detail, add_donasi, upload_bukti

app_name = "donasi"

urlpatterns = [
    path('', donasi_index, name='index'),
    path('add', add_donasi, name='form'),
    path('detail', donasi_detail, name='detail'),
    path('bukti', upload_bukti, name='bukti'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

penggalangan_dana/urls.py
from django.urls import path
from .views import form_pd_rumahibadah, index, add_pd, form_kesehatan, form_rumah_ibadah, form_pd, baru_kesehatan, tidak_baru_kesehatan, baru_rumah_ibadah, tidak_baru_rumah_ibadah, daftar_pd_pribadi, detail_pd, form_pd_kes, form_pd_rumahibadah

app_name = "penggalangan_dana"

urlpatterns = [
    path('',index, name='index'),
    path('add-pd/', add_pd, name='add_pd'),
    path('form-kesehatan/', form_kesehatan, name='form_kesehatan'),
    path('form-rumah_ibadah/', form_rumah_ibadah, name='form_rumah_ibadah'),
    path('form-pd/', form_pd, name='form_pd'),
    path('form-pd-kes/', form_pd_kes, name='form_pd_kes'),
    path('form-pd-rumahibadah/', form_pd_rumahibadah, name='form_pd_rumahibadah'),
    path('form-kesehatan/baru/', baru_kesehatan, name='baru_kesehatan'),
    path('form-kesehatan/tidak-baru/', tidak_baru_kesehatan, name='tidak_baru_kesehatan'),
    path('form-rumah_ibadah/baru/', baru_rumah_ibadah, name='baru_rumah_ibadah'),
    path('form-rumah_ibadah/tidak-baru/', tidak_baru_rumah_ibadah, name='tidak_baru_rumah_ibadah'),
    path('form-pd/daftar-pd-pribadi/', daftar_pd_pribadi, name='daftar_pd_pribadi'),
    path('detail-pd', detail_pd, name='detail_pd'),
]

sidona19/urls.py
from django.contrib import admin
from django.urls import include, path
import trigger3.urls as trigger3

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger3/', include(trigger3)),
    path('', include('login.urls')),
     path('trigger5/', include('trigger5.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('donasi/', include('donasi.urls')),
    path('penggalangan_dana/', include('penggalangan_dana.urls')),
    path('penyakit_komorbid/',include('penyakit_komorbid.urls')),
]

wishlist/urls.py
from django.urls import path
from .views import wishlist_index, wishlist_profile

app_name = "wishlist"

urlpatterns = [
    path('', wishlist_index, name='index'),
    path('profile', wishlist_profile, name='profile'),
]

wishlist/models.py
from django.db import models

# Create your models here.

wishlist/views.py
from django.shortcuts import render
from django.db import connection
from collections import namedtuple

# Create your views here.
# def wishlist_index(request) :
#     return render(request, 'wishlist_main.html')

def wishlist_index(request) :
    cursor = connection.cursor()
    cursor.execute("set search_path to sidona")
    cursor.execute("""
        select w.idpd, p.judul, k.nama_kategori from wishlist_donasi w
            join penggalangan_dana_pd p on w.idpd = p.id
            join kategori_pd k on p.id_kategori = k.id""")
    wishlist = namedtuplefetchall(cursor)
    jumlah_wishlist = len(wishlist)
    response = {
        'wishlist' : wishlist,
        'jumlah' : jumlah_wishlist,
    }
    return render(request, 'wishlist_main.html', response)

# def wishlist_profile(request) :
#     return render(request, 'wishlist_profile.html')

def wishlist_profile(request) :
    cursor = connection.cursor()
    cursor.execute("set search_path to sidona")
    cursor.execute("""
        select w.idpd, p.judul, k.nama_kategori from wishlist_donasi w
            join penggalangan_dana_pd p on w.idpd = p.id
            join kategori_pd k on p.id_kategori = k.id""")
    wishlist = namedtuplefetchall(cursor)
    jumlah_wishlist = len(wishlist)
    response = {
        'wishlist' : wishlist,
        'jumlah' : jumlah_wishlist,
    }
    return render(request, 'wishlist_profile.html', response)

def namedtuplefetchall(cursor):
        "Return all rows from a cursor as a namedtuple"
        desc = cursor.description
        nt_result = namedtuple('Result', [col[0] for col in desc])
        return [nt_result(*row) for row in cursor.fetchall()]

wishlist/templates/wishlist_detail.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}

<title>Sidona19 - Detail Donasi</title>

<!-- Ikon di tab -->
<!-- <link rel="icon" href="/static/favicon.svg">
<link rel="mask-icon" href="/static/favicon.svg" color="#000000"> -->

<!-- CSS Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- CSS Handmade -->
<link href="{% static 'css/wishlist_style.css' %}" rel="stylesheet"></link>

<!-- Buat Navbar -->
<!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"
integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> -->

<!-- Buat Ajax -->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->

{% endblock meta %}



{% block content %}

<!-- Untuk menampilkan navbar -->
<!-- {% include 'navbar.html'%} -->

<!-- Main Implementation -->
<div class="container-dim">
  <div class="card" style="width:700px; border-radius: 20px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);">

  <h1 style="text-align: center; padding: 40px;"><b>Detail Donasi</b></h1>
  
  <div class="d-flex flex-column container-dim" style="width:600px; padding: 4px;">
    
    <form action="" method="POST">
    <!-- {% csrf_token %} -->
    
    <div class="form-group" style="padding: 10px;">
      <label for='email' class="form-label">Email Donatur</label>
      <input id='email' class="form-control" type="text" placeholder="hbavidge0@squidoo.com" readonly>
    </div>
          
    <div class="form-group" style="padding: 10px;">
      <label for='timestamp' class="form-label">Timestamp</label>
      <input id='timestamp' class="form-control" type="text" placeholder="23.55" readonly>
    </div>

    <div class="form-group" style="padding: 10px;">
      <label for='judul' class="form-label">Judul Penggalangan Dana</label>
      <input id='judul' class="form-control" type="text" placeholder="Bantu Kelompok A-19 Lulus Basdat" readonly>
    </div>
  
    <div class="form-group" style="padding: 10px;">
      <label for='nominal' class="form-label">Nominal (Rupiah)</label>
      <input id='nominal' class="form-control" type="number" placeholder="120000" readonly>
    </div>

    <div id="bayar-anonim" class="row" style="padding: 10px;">
      <div class="col form-group">
        <label for="payment">Metode Pembayaran</label>
        <input id='judul' class="form-control" type="text" placeholder="Transfer" readonly>
      </div>
      <div class="col form-group">
        <label for="status">Status Anonim</label>
        <input id='judul' class="form-control" type="text" placeholder="Tidak" readonly>
      </div>
    </div>
          
    <div class="form-group" style="padding: 10px;">
      <label for='doa' class="form-label">Doa</label>
      <textarea class="form-control" id="doa" rows="3" placeholder="smoga lulus amien" readonly></textarea>
    </div>
  
    <div class="container-dim">
      <div class="tombol">
        <!-- {% csrf_token %} -->
        <a type="button" class="btn btn-outline-primary" href="{% url 'donasi:index' %}" >Kembali</a>
      </div>
    </div>
            
    </form>
  </div>
  </div>
</div>


<!-- <script src="{% static 'js/agenda_script.js' %}"></script> -->
{% endblock content %}

wishlist/templates/wishlist_main.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}

<title>Sidona19 - Daftar Wishlist</title>

<!-- CSS Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- CSS Handmade -->
<link href="{% static 'css/donasi_style.css' %}" rel="stylesheet"></link>

<!-- Buat jQuery & Ajax -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% endblock meta %}



{% block content %}

<!-- Untuk menampilkan navbar -->
<!-- {% include 'navbar.html'%} -->

<!-- Main Implementation -->
<div class="container-dim">
  <div class="card" style="width:900px; padding: 40px; border-radius: 20px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);">
    
  <h1 style="text-align: center; padding-bottom: 40px;"><b>Wishlist Donasi</b></h1>
  
  <div id="wishlist-profile">
    <table class="table table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col" style="width: 10%;">ID</th>
          <th scope="col" style="width: 40%;">Judul</th>
          <th scope="col" style="width: 30%;">Kategori</th>
          <th scope="col" style="width: 20%;">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for row in wishlist %}
        <tr>
          <th scope="row">{{row.idpd}}</th>
          <td>{{row.judul}}</td>
          <td>{{row.nama_kategori}}</td>
          <td>
            <div class="tombol-column">
              <a type="button" class="btn btn-secondary tombol-dim" href="{% url 'penggalangan_dana:detail_pd' %}">Detail</a>
              <a type="button" class="btn btn-success tombol-dim" href="{% url 'donasi:form' %}">Donasi</a>
              <a type="button" class="btn btn-danger tombol-dim" href="{% url 'wishlist:index' %}">Hapus</a>
            </div>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  
    <h6 style="text-align: left;">Jumlah Wishlist: {{jumlah}}</h6>
  </div>

  <div class="container-dim">
    <div class="tombol">
      <a type="button" class="btn btn-outline-primary" href="javascript:window.history.back();" >Kembali</a>
    </div>
  </div>

  </div>
  </div>


<!-- <script src="{% static 'js/agenda_script.js' %}"></script> -->
{% endblock content %}

wishlist/templates/wishlist_profile.html
{% load static %}

<!DOCTYPE html>
<div id="wishlist-profile">
    <table class="table table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col" style="width: 10%;">ID</th>
          <th scope="col" style="width: 40%;">Judul</th>
          <th scope="col" style="width: 30%;">Kategori</th>
          <th scope="col" style="width: 20%;">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for row in wishlist %}
        <tr>
          <th scope="row">{{row.idpd}}</th>
          <td>{{row.judul}}</td>
          <td>{{row.nama_kategori}}</td>
          <td>
            <div class="tombol-column">
              <a type="button" class="btn btn-secondary tombol-dim" href="{% url 'penggalangan_dana:detail_pd' %}">Detail</a>
              <a type="button" class="btn btn-success tombol-dim" href="{% url 'donasi:form' %}">Donasi</a>
              <a type="button" class="btn btn-danger tombol-dim" href="{% url 'wishlist:index' %}">Hapus</a>
            </div>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  
    <h6 style="text-align: left;">Jumlah Wishlist: {{jumlah}}</h6>
</div>
</html>