donasi/urls.py
from django.urls import path
from .views import donasi_index, donasi_detail, add_donasi, upload_bukti

app_name = "donasi"

urlpatterns = [
    path('', donasi_index, name='index'),
    path('add', add_donasi, name='form'),
    path('detail', donasi_detail, name='detail'),
    path('bukti', upload_bukti, name='bukti'),
]

login/urls.py
from django.urls import path
from .views import *

app_name = "login"

urlpatterns = [
    path('login', index, name='index'),
    path('', home, name='home'),
    path('register2', register2, name='register2'),
    path('register', register, name='register'),
    path('register_admin', register_admin, name='register_admin'),
    path('profile', profile, name='profile'),
    path('home', login,name='home'),
    path('logout', logout,name='logout'),
    

    
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

penggalangan_dana/urls.py
from django.urls import path
from .views import form_pd_rumahibadah, index, add_pd, form_kesehatan, form_rumah_ibadah, form_pd, baru_kesehatan, tidak_baru_kesehatan, baru_rumah_ibadah, tidak_baru_rumah_ibadah, daftar_pd_pribadi, detail_pd, form_pd_kes, form_pd_rumahibadah

app_name = "penggalangan_dana"

urlpatterns = [
    path('',index, name='index'),
    path('add-pd/', add_pd, name='add_pd'),
    path('form-kesehatan/', form_kesehatan, name='form_kesehatan'),
    path('form-rumah_ibadah/', form_rumah_ibadah, name='form_rumah_ibadah'),
    path('form-pd/', form_pd, name='form_pd'),
    path('form-pd-kes/', form_pd_kes, name='form_pd_kes'),
    path('form-pd-rumahibadah/', form_pd_rumahibadah, name='form_pd_rumahibadah'),
    path('form-kesehatan/baru/', baru_kesehatan, name='baru_kesehatan'),
    path('form-kesehatan/tidak-baru/', tidak_baru_kesehatan, name='tidak_baru_kesehatan'),
    path('form-rumah_ibadah/baru/', baru_rumah_ibadah, name='baru_rumah_ibadah'),
    path('form-rumah_ibadah/tidak-baru/', tidak_baru_rumah_ibadah, name='tidak_baru_rumah_ibadah'),
    path('form-pd/daftar-pd-pribadi/', daftar_pd_pribadi, name='daftar_pd_pribadi'),
    path('detail-pd', detail_pd, name='detail_pd'),
]

sidona19/urls.py
from django.contrib import admin
from django.urls import include, path
import trigger3.urls as trigger3

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger3/', include(trigger3)),
    path('', include('login.urls')),
     path('trigger5/', include('trigger5.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('donasi/', include('donasi.urls')),
    path('penggalangan_dana/', include('penggalangan_dana.urls')),
    path('penyakit_komorbid/',include('penyakit_komorbid.urls')),
]

trigger3/urls.py
from django.urls import path

from . import views

app_name = 'trigger3'

urlpatterns = [
    path('read_penggalangan_admin', views.read_penggalangan_admin, name='read_penggalangan_admin'),
    path('read_penggalangan_admin/<str:id>', views.create_catatan_pengajuan, name='create_catatan_pengajuan'),
    path('read_penggalangan_user', views.read_penggalangan_user, name='read_penggalangan_user'),
    path('read_penggalangan_user/<str:id>', views.update_penggalangan, name='update_penggalangan'),
    path('read_catatan_pengajuan', views.read_catatan_pengajuan, name='read_catatan_pengajuan'),
    path('create_kategori', views.create_kategori, name='create_kategori'),
    path('read_kategori', views.read_kategori, name='read_kategori'),
    path('read_kategori/<str:id>', views.update_kategori, name='update_kategori'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description"
    content="SIDON-19 adalah sistem informasi donasi untuk bantuan covid-19">
  
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <div id="loader-container">
    <div id="loader">Loading...</div>
  </div>
  <div id="root">
    {% include 'navbar.html' %}

    <main>
     
   


      <div class="container">
        {% block content %}
        {% endblock content %}
      </div>
    </main>
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" ></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/@reliutg/buzz-notify/index.min.js"></script>
  
  <script src="{% static 'js/script.js' %}"></script>

  {% block js %}
   
	
  {% endblock js %}
</body>

</html>

templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/navbar.html
{%load static%}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid container">
   
    <a class="navbar-brand" href="#">SIDONA 19</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-lg-row justify-content-between" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
       




        {% if request.session.role %}
		<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Data Penggalang Dana
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Daftar Penggalangan Dana Pribadi</a></li>
         
         
          </ul>
        </li>
		
		<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Penggalang Dana
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'penggalangan_dana:add_pd' %}">Buat </a></li>
            <li><a class="dropdown-item" href="{% url 'trigger3:read_kategori' %}">Read Kategori </a></li>
            <li><a class="dropdown-item" href="{% url 'trigger3:create_kategori' %}">Create Kategori </a></li>
            <li><a class="dropdown-item" href="{% url 'trigger3:read_penggalangan_admin' %}">Read Penggalangan Dana - Admin</a></li>
            <li><a class="dropdown-item" href="{% url 'trigger3:read_penggalangan_user' %}">Read Penggalangan Dana - Pengguna</a></li>
            <li><a class="dropdown-item" href="{% url 'trigger3:read_catatan_pengajuan' %}">Read Catatan Pengajuan</a></li>
			<li><a class="dropdown-item" href="{% url 'penyakit_komorbid:index' %}">Kelola Penyakit Komorbid</a></li>
          </ul>
        </li>
	
		




		
		
		<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Donasi
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'donasi:index' %}">Daftar Donasi</a></li>
            
          </ul>
        </li>
		
		
			
		
		
		<li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Daftar Pengguna</a>
        </li>
        {% endif %}
      
      {% if  request.session.role == 'penggalang_dana' %}
		  <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'login:profile' %}">Profil</a>
        </li>
        {% endif %}
		
		
		
  
		
	  
      
      {% if hasil  %}

      <a href="/logout">
        <button type="button" class="btn btn-danger">Logout</button>
      </a>

      {% else %}
      <a href="/login">
        <button type="button" class="btn btn-success">Login</button>
      </a>
      <a href="register">
        <button type="button" class="btn btn-success">Signup</button>
         </a>

      {% endif %}
    
   
		
    </div>
  </div>
</nav>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>