donasi/urls.py
from django.urls import path
from .views import donasi_index, donasi_detail, add_donasi, upload_bukti

app_name = "donasi"

urlpatterns = [
    path('', donasi_index, name='index'),
    path('add', add_donasi, name='form'),
    path('detail', donasi_detail, name='detail'),
    path('bukti', upload_bukti, name='bukti'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sidona19/urls.py
from django.contrib import admin
from django.urls import include, path
import trigger3.urls as trigger3

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger3/', include(trigger3)),
    path('', include('login.urls')),
     path('trigger5/', include('trigger5.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('donasi/', include('donasi.urls')),
    path('penggalangan_dana/', include('penggalangan_dana.urls')),
    path('penyakit_komorbid/',include('penyakit_komorbid.urls')),
]

donasi/models.py
from django.db import models

# Create your models here.

donasi/forms.py
from django import forms

class AddDonasiForm(forms.Form):
    email = forms.CharField(label = 'Email', max_length=50)
    password = forms.CharField(label = 'Password',  widget=forms.PasswordInput, max_length=128)

donasi/views.py
from django.http import response
from django.shortcuts import render, redirect
from django.db import connection
from collections import namedtuple

# Create your views here.
def donasi_index(request):
    # email = request.session['email']
    cursor = connection.cursor()
    cursor.execute("set search_path to sidona")
    # cursor.execute("select * from donasi d join status_pembayaran s on d.idstatuspembayaran = s.id")
    cursor.execute('''
        select d.idpd, p.judul, k.nama_kategori, s.status from donasi d
        join status_pembayaran s on d.idstatuspembayaran = s.id
        join penggalangan_dana_pd p on d.idpd = p.id
        join kategori_pd k on p.id_kategori = k.id''')
    donasi = namedtuplefetchall(cursor)
    context = {
        'donasi' : donasi,
    }
    return render(request, 'donasi_index.html', context)
    
    # try:
    #     email = str(request.session['email'])
    # except Exception as e:
    #     return redirect('/')

    # cursor = connection.cursor()
    # cursor.execute("set search_path to sidona")
    # # cursor.execute("select * from donasi d join status_pembayaran s on d.idstatuspembayaran = s.id")
    # cursor.execute("""
    #     select d.email, d.idpd, p.judul, k.nama_kategori, s.status from donasi d
    #     join status_pembayaran s on d.idstatuspembayaran = s.id
    #     join penggalangan_dana_pd p on d.idpd = p.id
    #     join kategori_pd k on p.id_kategori = k.id
    #     where d.email = '""" + email + "'")
    # donasi = namedtuplefetchall(cursor)
    # context = {
    #     'donasi' : donasi,
    # }
    # return render(request, 'donasi_index.html', context)

def add_donasi(request):
    return render(request, 'donasi_form.html')

def upload_bukti(request):
    return render(request, 'donasi_form_bukti.html')

def donasi_detail(request):
    return render(request, 'donasi_detail.html')

def namedtuplefetchall(cursor):
        "Return all rows from a cursor as a namedtuple"
        desc = cursor.description
        nt_result = namedtuple('Result', [col[0] for col in desc])
        return [nt_result(*row) for row in cursor.fetchall()]

donasi/templates/donasi_detail.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}

<title>Sidona19 - Detail Donasi</title>

<!-- CSS Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- CSS Handmade -->
<link href="{% static 'css/donasi_style.css' %}" rel="stylesheet"></link>

<!-- Buat jQuery & Ajax -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% endblock meta %}



{% block content %}

<!-- Main Implementation -->
<div class="container-dim">
  <div class="card" style="width:700px; border-radius: 20px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);">

  <h1 style="text-align: center; padding: 40px;"><b>Detail Donasi</b></h1>
  
  <div class="d-flex flex-column container-dim" style="width:600px; padding: 4px;">
    
    <form action="" method="POST">
    <!-- {% csrf_token %} -->
    
    <div class="form-group" style="padding: 10px;">
      <label for='email' class="form-label">Email Donatur</label>
      <input id='email' class="form-control" type="text" placeholder="hbavidge0@squidoo.com" readonly>
    </div>
          
    <div class="form-group" style="padding: 10px;">
      <label for='timestamp' class="form-label">Timestamp</label>
      <input id='timestamp' class="form-control" type="text" placeholder="23.55" readonly>
    </div>

    <div class="form-group" style="padding: 10px;">
      <label for='judul' class="form-label">Judul Penggalangan Dana</label>
      <input id='judul' class="form-control" type="text" placeholder="Bantu Kelompok A-19 Lulus Basdat" readonly>
    </div>
  
    <div class="form-group" style="padding: 10px;">
      <label for='nominal' class="form-label">Nominal (Rupiah)</label>
      <input id='nominal' class="form-control" type="number" placeholder="120000" readonly>
    </div>

    <div id="bayar-anonim" class="row" style="padding: 10px;">
      <div class="col form-group">
        <label for="payment">Metode Pembayaran</label>
        <input id='judul' class="form-control" type="text" placeholder="Transfer" readonly>
      </div>
      <div class="col form-group">
        <label for="status">Status Anonim</label>
        <input id='judul' class="form-control" type="text" placeholder="Tidak" readonly>
      </div>
    </div>
          
    <div class="form-group" style="padding: 10px;">
      <label for='doa' class="form-label">Doa</label>
      <textarea class="form-control" id="doa" rows="3" placeholder="smoga lulus amien" readonly></textarea>
    </div>
  
    <div class="container-dim">
      <div class="tombol">
        <a type="button" class="btn btn-outline-primary" href="javascript:window.history.back();" >Kembali</a>
      </div>
    </div>
            
    </form>
  </div>
  </div>
</div>


<!-- <script src="{% static 'js/agenda_script.js' %}"></script> -->
{% endblock content %}

donasi/templates/donasi_form.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}

<title>Sidona19 - Donasi</title>

<!-- Ikon di tab -->
<!-- <link rel="icon" href="/static/favicon.svg">
<link rel="mask-icon" href="/static/favicon.svg" color="#000000"> -->

<!-- CSS Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- CSS Handmade -->
<link href="{% static 'css/donasi_style.css' %}" rel="stylesheet"></link>

<!-- Buat Navbar -->
<!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"
integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> -->

<!-- Buat Ajax -->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->

{% endblock meta %}



{% block content %}

<!-- Untuk menampilkan navbar -->
<!-- {% include 'navbar.html'%} -->

<!-- Main Implementation -->
<div class="container-dim">
  <div class="card" style="width:700px; border-radius: 20px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);">

  <h1 style="text-align: center; padding: 40px;"><b>Form Pembuatan Donasi</b></h1>
  
  <div class="d-flex flex-column container-dim" style="width:600px; padding: 4px;">

    <h3 style="text-align: center;">Informasi Umum Donasi</h3>
    
    <form action="" method="POST">
    <!-- {% csrf_token %} -->
    
    <div class="form-group" style="padding: 10px;">
      <label for='email' class="form-label">Email Donatur</label>
      <input id='email' class="form-control" type="text" placeholder="nama-email@aaa.com" readonly>
    </div>
          
    <div class="form-group" style="padding: 10px;">
      <label for='timestamp' class="form-label">Timestamp</label>
      <input id='timestamp' class="form-control" type="text" placeholder="23.55" readonly>
    </div>

    <div class="form-group" style="padding: 10px;">
      <label for='judul' class="form-label">Judul Penggalangan Dana</label>
      <input id='judul' class="form-control" type="text" placeholder="Bantu Kelompok A-19 Lulus Basdat" readonly>
    </div>
  
    <div class="form-group" style="padding: 10px;">
      <label for='nominal' class="form-label">Nominal (Rupiah)</label>
      <input id='nominal' class="form-control" type="number" placeholder="2000000">
    </div>

    <div id="bayar-anonim" class="row" style="padding: 10px;">
      <!-- <label for='tenggat' class="form-label" >Pembayaran</label> -->
      <div class="col form-group">
        <label for="payment">Metode Pembayaran</label>
        <select class="form-control" id="payment">
          <option>Transfer</option>
          <option>DonaPay</option>
        </select>
      </div>
      <div class="col form-group">
        <label for="status">Status Anonim</label>
        <select class="form-control" id="status">
          <option>Ya</option>
          <option>Tidak</option>
        </select>
      </div>
    </div>
          
    <div class="form-group" style="padding: 10px;">
      <label for='doa' class="form-label">Doa</label>
      <textarea class="form-control" id="doa" rows="3"></textarea>
    </div>
  
    <div class="container-dim">
      <div class="tombol">
        <!-- {% csrf_token %} -->
        <!-- <a type="button" class="btn btn-outline-danger" href="{% url 'donasi:index' %}" >Batal</a> -->
        <a type="button" class="btn btn-outline-danger" href="javascript:window.history.back();" >Batal</a>
        <input type="submit" class="btn btn-primary justify-content-center" value="Buat Donasi" href="{% url 'donasi:index' %}">
      </div>
    </div>
            
    </form>
  </div>
  </div>
</div>


<!-- <script src="{% static 'js/donasi_script.js' %}"></script> -->
{% endblock content %}

donasi/templates/donasi_form_bukti.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}

<title>Sidona19 - Upload Bukti Donasi</title>

<!-- Ikon di tab -->
<!-- <link rel="icon" href="/static/favicon.svg">
<link rel="mask-icon" href="/static/favicon.svg" color="#000000"> -->

<!-- CSS Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- CSS Handmade -->
<link href="{% static 'css/donasi_style.css' %}" rel="stylesheet"></link>

<!-- Buat Navbar -->
<!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"
integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> -->

<!-- Buat Ajax -->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->

{% endblock meta %}



{% block content %}

<!-- Untuk menampilkan navbar -->
<!-- {% include 'navbar.html'%} -->

<!-- Main Implementation -->
<div class="container-dim">
  <div class="card" style="width:700px; border-radius: 20px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);">

  <h1 style="text-align: center; padding: 40px;"><b>Upload Bukti Donasi</b></h1>
  
  <div class="d-flex flex-column container-dim" style="width:600px; padding: 4px;">

    <!-- <h3 style="text-align: center;">Informasi Umum Donasi</h3> -->
    
    <form action="" method="POST">
    <!-- {% csrf_token %} -->
    
    <div class="form-group" style="padding: 10px;">
      <label for='email' class="form-label">Email Donatur</label>
      <input id='email' class="form-control" type="text" placeholder="nama-email@aaa.com" readonly>
    </div>

    <div class="form-group" style="padding: 10px;">
      <label for='judul' class="form-label">Judul Penggalangan Dana</label>
      <input id='judul' class="form-control" type="text" placeholder="Bantu Kelompok A-19 Lulus Basdat" readonly>
    </div>
  
    <div class="form-group" style="padding: 10px;">
      <label for='nominal' class="form-label">Bukti</label>
      <input type="file" class="form-control" value="Upload Bukti">
    </div>
  
    <div class="container-dim">
      <div class="tombol">
        <!-- {% csrf_token %} -->
        <a type="button" class="btn btn-outline-danger" href="{% url 'donasi:index' %}" >Batal</a>
        <input type="submit" class="btn btn-primary justify-content-center" value="Tambahkan ke Agenda" href="{% url 'donasi:index' %}">
      </div>
    </div>
            
    </form>
  </div>
  </div>
  </div>


<!-- <script src="{% static 'js/donasi_script.js' %}"></script> -->
{% endblock content %}

donasi/templates/donasi_index.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}

<title>Sidona19 - Daftar Donasi</title>

<!-- CSS Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- CSS Handmade -->
<link href="{% static 'css/donasi_style.css' %}" rel="stylesheet"></link>

<!-- Buat jQuery & Ajax -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% endblock meta %}



{% block content %}

<!-- Main Implementation -->
<div class="container-dim">
  <div class="card" style="width:1200px; padding: 40px; border-radius: 20px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);">
    
  <h1 style="text-align: center; padding-bottom: 40px;"><b>Data Donasi Penggalangan Dana</b></h1>
  
  <table id="tabelDonasi" class="table table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col" style="width: 10%;">ID</th>
        <th scope="col" style="width: 30%;">Judul</th>
        <th scope="col" style="width: 20%;">Kategori</th>
        <th scope="col" style="width: 20%;">Status Pembayaran</th>
        <th scope="col" style="width: 20%;">Action</th>
      </tr>
    </thead>

    <tbody>
      {% for row in donasi %}
      <tr>
        <th scope="row">{{row.idpd}}</th>
        <td>{{row.judul}}</td>
        <td>{{row.nama_kategori}}</td>
        <td> <var id="status">{{row.status}}</var> </td>

        <td>
          <div id="tombolStatus" class="tombol-column">
            <!-- Default ada ini semua -->
            <a type="button" class="btn btn-secondary tombol-dim" href="{% url 'donasi:detail' %}">Detail</a>
            <!-- Menunggu pembayaran -->
            <a type="button" class="btn btn-primary tombol-dim" href="{% url 'donasi:bukti' %}">Upload Bukti</a>
            <!-- Pengecekan & Sukses -->
            <a type="button" class="btn btn-info tombol-dim" href="{% static 'images/dummy-tf.jpg' %}" target="_blank">Lihat Bukti</a>
            <!-- Dibatalkan -> hanya ada tombol detail -->

            
            <!-- <script>
              (function addAction() {
                var innerHTML = `<a type="button" class="btn btn-secondary tombol-dim" href="{% url 'donasi:detail' %}">Detail</a>`;
                var status = document.getElementById("status");
                if (status == "dibatalkan") {
                  // gausah ditambah apa2
                } else if (status == "sukses") {
                  innerHTML += `<a type="button" class="btn btn-info tombol-dim" href="{% static 'images/dummy-tf.jpg' %}" target="_blank">Lihat Bukti</a>`;
                } else {
                  innerHTML += `<a type="button" class="btn btn-primary tombol-dim" href="{% url 'donasi:bukti' %}">Upload Bukti</a> `;
                }
                document.getElementById("tombolStatus").innerHTML = innerHTML;
              })();
            </script> -->
            <!-- <script>addAction();</script> -->
            <!-- <a type="button" class="btn btn-secondary tombol-dim" href="{% url 'donasi:detail' %}">Detail</a>
            <a type="button" class="btn btn-primary tombol-dim" href="{% url 'donasi:bukti' %}">Upload Bukti</a> -->
            <!-- <form action="">
              <input type="file" class="btn btn-primary tombol-dim" value="Upload Bukti">
            </form> -->
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  
  </div>
  </div>

<script>
  (jQuery(function($) {
    $('#tabelDonasi').each(function() {
      var innerHTML = `<a type="button" class="btn btn-secondary tombol-dim" href="{% url 'donasi:detail' %}">Detail</a>`;
      var status = document.getElementById("status");
      if (status == "dibatalkan") {
        // gausah ditambah apa2
      } else if (status == "sukses") {
        innerHTML += `<a type="button" class="btn btn-info tombol-dim" href="{% static 'images/dummy-tf.jpg' %}" target="_blank">Lihat Bukti</a>`;
      } else {
        innerHTML += `<a type="button" class="btn btn-primary tombol-dim" href="{% url 'donasi:bukti' %}">Upload Bukti</a> `;
      }
      document.getElementById("tombolStatus").innerHTML = innerHTML;
    });
  }))();
  
  // jQuery(function($) {
  //   $('#tabelDonasi').each(function() {
  //     var innerHTML = `<a type="button" class="btn btn-secondary tombol-dim" href="{% url 'donasi:detail' %}">Detail</a>`;
  //     var status = document.getElementById("status");
  //     if (status == "dibatalkan") {
  //       // gausah ditambah apa2
  //     } else if (status == "sukses") {
  //       innerHTML += `<a type="button" class="btn btn-info tombol-dim" href="{% static 'images/dummy-tf.jpg' %}" target="_blank">Lihat Bukti</a>`;
  //     } else {
  //       innerHTML += `<a type="button" class="btn btn-primary tombol-dim" href="{% url 'donasi:bukti' %}">Upload Bukti</a> `;
  //     }
  //     document.getElementById("tombolStatus").innerHTML = innerHTML;
  //   });
  // })

  // function addAction(){
  //   var status = document.getElementById("status");
  //   if (status == "dibatalkan") {
  //     $("#tombolStatus").html(`
  //       <a type="button" class="btn btn-secondary tombol-dim" href="{% url 'donasi:detail' %}">Detail</a> `);
  //   } else if (status == "sukses") {
  //     $("#tombolStatus").html(`
  //       <a type="button" class="btn btn-secondary tombol-dim" href="{% url 'donasi:detail' %}">Detail</a>
  //       <a type="button" class="btn btn-info tombol-dim" href="{% static 'images/dummy-tf.jpg' %}" target="_blank">Lihat Bukti</a> `);
  //   } else {
  //     $("#tombolStatus").html(`
  //       <a type="button" class="btn btn-secondary tombol-dim" href="{% url 'donasi:detail' %}">Detail</a>
  //       <a type="button" class="btn btn-primary tombol-dim" href="{% url 'donasi:bukti' %}">Upload Bukti</a> `);
  //   }
  // };

  // function addAction(){
  //   var innerHTML = `<a type="button" class="btn btn-secondary tombol-dim" href="{% url 'donasi:detail' %}">Detail</a>`;
  //   var status = document.getElementById("status");
  //   if (status == "dibatalkan") {
  //     // gausah ditambah apa2
  //   } else if (status == "sukses") {
  //     innerHTML += `<a type="button" class="btn btn-info tombol-dim" href="{% static 'images/dummy-tf.jpg' %}" target="_blank">Lihat Bukti</a>`;
  //   } else {
  //     innerHTML += `<a type="button" class="btn btn-primary tombol-dim" href="{% url 'donasi:bukti' %}">Upload Bukti</a> `;
  //   }
  //   document.getElementById("tombolStatus").innerHTML = innerHTML;
  // };

  // document.addEventListener("DOMContentLoaded", function(event) {
  //   var innerHTML = `<a type="button" class="btn btn-secondary tombol-dim" href="{% url 'donasi:detail' %}">Detail</a>`;
  //   var status = document.getElementById("status");
  //   if (status == "dibatalkan") {
  //     // gausah ditambah apa2
  //   } else if (status == "sukses") {
  //     innerHTML += `<a type="button" class="btn btn-info tombol-dim" href="{% static 'images/dummy-tf.jpg' %}" target="_blank">Lihat Bukti</a>`;
  //   } else {
  //     innerHTML += `<a type="button" class="btn btn-primary tombol-dim" href="{% url 'donasi:bukti' %}">Upload Bukti</a> `;
  //   }
  //   document.getElementById("tombolStatus").innerHTML = innerHTML;
  // });

</script>
<!-- <script src="{% static 'js/agenda_script.js' %}"></script> -->
{% endblock content %}